"""
Turns one incident record into the two documents a real breach requires:
a CERT-In incident report (mirroring CERT-In's own published Incident
Reporting Form) and a DPDP Board breach notification (structured on the
fields the DPDP Rules require to be conveyed -- nature of breach, categories
and approximate number of data principals affected, likely consequences,
mitigation measures, and a contactable person).

Unknown fields are marked "Under investigation" rather than left blank --
CERT-In's own guidance is to submit with known fields filled and gaps
explicitly marked, not to wait for a complete picture.
"""

from reference_data import CERT_IN_TYPE_LABELS


def _val(v, placeholder="Under investigation"):
    if v is None or v == "":
        return placeholder
    return v


def build_cert_in_report(incident: dict, org: dict) -> dict:
    type_labels = [CERT_IN_TYPE_LABELS.get(t, t) for t in incident.get("incident_types", [])]
    return {
        "reporter": {
            "name": _val(org.get("poc_name")),
            "role_title": _val(org.get("poc_role")),
            "organization_name": _val(org.get("org_name")),
            "contact_no": _val(org.get("poc_contact")),
            "email": _val(org.get("poc_email")),
            "address": _val(org.get("address")),
        },
        "affected_entity": _val(incident.get("affected_entity_name") or org.get("org_name")),
        "incident_types": type_labels or ["Under investigation"],
        "incident_type_other": _val(incident.get("incident_type_other"), ""),
        "is_critical_system": "Yes" if incident.get("is_critical_system") else "No",
        "critical_details": _val(incident.get("critical_details"), ""),
        "affected_system": {
            "domain_url": _val(incident.get("domain_url")),
            "ip_address": _val(incident.get("ip_address")),
            "operating_system": _val(incident.get("operating_system")),
            "make_model_cloud": _val(incident.get("make_model_cloud")),
            "affected_application": _val(incident.get("affected_application")),
            "location": ", ".join(
                p for p in [incident.get("location_city"), incident.get("location_region"), incident.get("location_country")] if p
            ) or "Under investigation",
            "network_isp": _val(incident.get("network_isp")),
        },
        "occurrence_datetime": _val(incident.get("occurrence_datetime"), "Unknown"),
        "detection_datetime": incident["detection_datetime"],
        "description": _val(incident.get("description")),
        "submit_to": {
            "email": "incident@cert-in.org.in",
            "phone": "1800-11-4949",
            "address": "CERT-In, Electronics Niketan, CGO Complex, New Delhi 110003",
        },
    }


def build_dpdp_report(incident: dict, org: dict, tier: str) -> dict:
    """tier is 'initial' or 'detailed'. The initial notice is short by design
    (DPDP requires it 'without delay') -- the detailed one carries the full
    fields the Rules expect within 72 hours."""
    base = {
        "data_fiduciary": _val(org.get("org_name")),
        "dpo_or_contact": {
            "name": _val(org.get("dpo_name") or org.get("poc_name")),
            "contact": _val(org.get("dpo_contact") or org.get("poc_contact")),
            "email": _val(org.get("dpo_email") or org.get("poc_email")),
        },
        "detection_datetime": incident["detection_datetime"],
        "nature_of_breach": _val(incident.get("description")),
    }
    if tier == "initial":
        base["note"] = (
            "Initial notice only -- DPDP Act requires notifying the Data "
            "Protection Board of India without delay upon becoming aware of "
            "a personal data breach. File this immediately; the detailed "
            "report follows within 72 hours."
        )
        return base

    base.update({
        "data_categories_affected": _val(incident.get("data_categories_affected")),
        "estimated_individuals_affected": incident.get("estimated_individuals_affected") or "Under investigation",
        "likely_consequences": _val(incident.get("likely_consequences")),
        "mitigation_measures": _val(incident.get("mitigation_measures")),
        "note": (
            "Detailed report -- due within 72 hours of becoming aware of the "
            "breach, per the DPDP Rules, 2025."
        ),
    })
    return base


def cert_in_report_text(report: dict) -> str:
    types = "\n".join(f"  - {t}" for t in report["incident_types"])
    return f"""CERT-IN INCIDENT REPORT
Generated by Prahari -- verify all fields before submission.

REPORTER
  Name / Role       : {report['reporter']['name']} / {report['reporter']['role_title']}
  Organization      : {report['reporter']['organization_name']}
  Contact No.       : {report['reporter']['contact_no']}
  Email             : {report['reporter']['email']}
  Address           : {report['reporter']['address']}

AFFECTED ENTITY
  {report['affected_entity']}

INCIDENT TYPE(S)
{types}
  Other             : {report['incident_type_other']}

CRITICALITY
  Critical to mission: {report['is_critical_system']}
  Details            : {report['critical_details']}

AFFECTED SYSTEM
  Domain/URL        : {report['affected_system']['domain_url']}
  IP Address        : {report['affected_system']['ip_address']}
  Operating System  : {report['affected_system']['operating_system']}
  Make/Model/Cloud  : {report['affected_system']['make_model_cloud']}
  Application       : {report['affected_system']['affected_application']}
  Location          : {report['affected_system']['location']}
  Network/ISP       : {report['affected_system']['network_isp']}

TIMING
  Occurred          : {report['occurrence_datetime']}
  Detected          : {report['detection_datetime']}

DESCRIPTION
  {report['description']}

SUBMIT TO
  Email : {report['submit_to']['email']}
  Phone : {report['submit_to']['phone']}
  Post  : {report['submit_to']['address']}
"""


def dpdp_report_text(report: dict, tier: str) -> str:
    header = "DPDP BOARD -- INITIAL BREACH NOTICE" if tier == "initial" else "DPDP BOARD -- DETAILED BREACH REPORT"
    lines = [
        header,
        "Generated by Prahari -- verify all fields before submission.",
        "",
        f"Data Fiduciary   : {report['data_fiduciary']}",
        f"DPO / Contact    : {report['dpo_or_contact']['name']} ({report['dpo_or_contact']['contact']}, {report['dpo_or_contact']['email']})",
        f"Detected         : {report['detection_datetime']}",
        f"Nature of breach : {report['nature_of_breach']}",
    ]
    if tier == "detailed":
        lines += [
            f"Data categories affected     : {report['data_categories_affected']}",
            f"Estimated individuals affected: {report['estimated_individuals_affected']}",
            f"Likely consequences          : {report['likely_consequences']}",
            f"Mitigation measures          : {report['mitigation_measures']}",
        ]
    lines += ["", report["note"]]
    return "\n".join(lines)
